/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubscriptionStatus = IDL.Variant({
  'trial' : IDL.Null,
  'active' : IDL.Null,
  'expired' : IDL.Null,
});
export const Time = IDL.Int;
export const AppUserProfile = IDL.Record({
  'uid' : IDL.Text,
  'status' : SubscriptionStatus,
  'username' : IDL.Text,
  'subscriptionExpiry' : Time,
});
export const PostCategory = IDL.Variant({
  'news' : IDL.Null,
  'post' : IDL.Null,
});
export const NewsPost = IDL.Record({
  'title' : IDL.Text,
  'postCategory' : PostCategory,
  'timestamp' : Time,
  'contentSummary' : IDL.Text,
});
export const Direction = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const SignalStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const TradingSignal = IDL.Record({
  'direction' : Direction,
  'targetPrice' : IDL.Float64,
  'stopLoss' : IDL.Float64,
  'timestamp' : Time,
  'coinName' : IDL.Text,
  'entryPrice' : IDL.Float64,
  'signalStatus' : SignalStatus,
});
export const CoinCategory = IDL.Variant({
  'hundredX' : IDL.Null,
  'trending' : IDL.Null,
});
export const TrendingCoin = IDL.Record({
  'currentPrice' : IDL.Float64,
  'change24h' : IDL.Float64,
  'name' : IDL.Text,
  'predictedTarget' : IDL.Float64,
  'category' : CoinCategory,
  'symbol' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'status' : SubscriptionStatus,
  'username' : IDL.Text,
  'subscriptionExpiry' : Time,
});
export const MarketSentiment = IDL.Variant({
  'bullish' : IDL.Null,
  'bearish' : IDL.Null,
  'neutral' : IDL.Null,
});
export const MarketStatus = IDL.Record({
  'btcDominance' : IDL.Float64,
  'marketCap' : IDL.Float64,
  'sentiment' : MarketSentiment,
});
export const ScanReport = IDL.Record({
  'totalSignalsGenerated' : IDL.Nat,
  'activeSignalsCount' : IDL.Nat,
  'winRate' : IDL.Float64,
  'totalCoinsScanned' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAppUserProfile' : IDL.Func([AppUserProfile], [], []),
  'addNewsPost' : IDL.Func([NewsPost], [], []),
  'addTradingSignal' : IDL.Func([TradingSignal], [], []),
  'addTrendingCoin' : IDL.Func([TrendingCoin], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllAppUserProfiles' : IDL.Func([], [IDL.Vec(AppUserProfile)], ['query']),
  'getAllNewsPosts' : IDL.Func([], [IDL.Vec(NewsPost)], ['query']),
  'getAllTradingSignals' : IDL.Func([], [IDL.Vec(TradingSignal)], ['query']),
  'getAllTrendingCoins' : IDL.Func([], [IDL.Vec(TrendingCoin)], ['query']),
  'getAppUserProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AppUserProfile)],
      ['query'],
    ),
  'getAppUserProfilesByStatus' : IDL.Func(
      [SubscriptionStatus],
      [IDL.Vec(AppUserProfile)],
      ['query'],
    ),
  'getAppUserProfilesBySubscriptionExpiry' : IDL.Func(
      [],
      [IDL.Vec(AppUserProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMarketStatus' : IDL.Func([], [MarketStatus], ['query']),
  'getNewsPost' : IDL.Func([IDL.Text], [IDL.Opt(NewsPost)], ['query']),
  'getNewsPostsByCategory' : IDL.Func(
      [PostCategory],
      [IDL.Vec(NewsPost)],
      ['query'],
    ),
  'getNewsPostsByTimestamp' : IDL.Func([], [IDL.Vec(NewsPost)], ['query']),
  'getScanReport' : IDL.Func([], [ScanReport], ['query']),
  'getTradingSignal' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TradingSignal)],
      ['query'],
    ),
  'getTradingSignalsByCoinName' : IDL.Func(
      [],
      [IDL.Vec(TradingSignal)],
      ['query'],
    ),
  'getTradingSignalsByStatus' : IDL.Func(
      [SignalStatus],
      [IDL.Vec(TradingSignal)],
      ['query'],
    ),
  'getTradingSignalsByTimestamp' : IDL.Func(
      [],
      [IDL.Vec(TradingSignal)],
      ['query'],
    ),
  'getTrendingCoin' : IDL.Func([IDL.Text], [IDL.Opt(TrendingCoin)], ['query']),
  'getTrendingCoinsByCategory' : IDL.Func(
      [CoinCategory],
      [IDL.Vec(TrendingCoin)],
      ['query'],
    ),
  'getTrendingCoinsByPrice' : IDL.Func([], [IDL.Vec(TrendingCoin)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMarketStatus' : IDL.Func([MarketStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubscriptionStatus = IDL.Variant({
    'trial' : IDL.Null,
    'active' : IDL.Null,
    'expired' : IDL.Null,
  });
  const Time = IDL.Int;
  const AppUserProfile = IDL.Record({
    'uid' : IDL.Text,
    'status' : SubscriptionStatus,
    'username' : IDL.Text,
    'subscriptionExpiry' : Time,
  });
  const PostCategory = IDL.Variant({ 'news' : IDL.Null, 'post' : IDL.Null });
  const NewsPost = IDL.Record({
    'title' : IDL.Text,
    'postCategory' : PostCategory,
    'timestamp' : Time,
    'contentSummary' : IDL.Text,
  });
  const Direction = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const SignalStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const TradingSignal = IDL.Record({
    'direction' : Direction,
    'targetPrice' : IDL.Float64,
    'stopLoss' : IDL.Float64,
    'timestamp' : Time,
    'coinName' : IDL.Text,
    'entryPrice' : IDL.Float64,
    'signalStatus' : SignalStatus,
  });
  const CoinCategory = IDL.Variant({
    'hundredX' : IDL.Null,
    'trending' : IDL.Null,
  });
  const TrendingCoin = IDL.Record({
    'currentPrice' : IDL.Float64,
    'change24h' : IDL.Float64,
    'name' : IDL.Text,
    'predictedTarget' : IDL.Float64,
    'category' : CoinCategory,
    'symbol' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'status' : SubscriptionStatus,
    'username' : IDL.Text,
    'subscriptionExpiry' : Time,
  });
  const MarketSentiment = IDL.Variant({
    'bullish' : IDL.Null,
    'bearish' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const MarketStatus = IDL.Record({
    'btcDominance' : IDL.Float64,
    'marketCap' : IDL.Float64,
    'sentiment' : MarketSentiment,
  });
  const ScanReport = IDL.Record({
    'totalSignalsGenerated' : IDL.Nat,
    'activeSignalsCount' : IDL.Nat,
    'winRate' : IDL.Float64,
    'totalCoinsScanned' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAppUserProfile' : IDL.Func([AppUserProfile], [], []),
    'addNewsPost' : IDL.Func([NewsPost], [], []),
    'addTradingSignal' : IDL.Func([TradingSignal], [], []),
    'addTrendingCoin' : IDL.Func([TrendingCoin], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllAppUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(AppUserProfile)],
        ['query'],
      ),
    'getAllNewsPosts' : IDL.Func([], [IDL.Vec(NewsPost)], ['query']),
    'getAllTradingSignals' : IDL.Func([], [IDL.Vec(TradingSignal)], ['query']),
    'getAllTrendingCoins' : IDL.Func([], [IDL.Vec(TrendingCoin)], ['query']),
    'getAppUserProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AppUserProfile)],
        ['query'],
      ),
    'getAppUserProfilesByStatus' : IDL.Func(
        [SubscriptionStatus],
        [IDL.Vec(AppUserProfile)],
        ['query'],
      ),
    'getAppUserProfilesBySubscriptionExpiry' : IDL.Func(
        [],
        [IDL.Vec(AppUserProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMarketStatus' : IDL.Func([], [MarketStatus], ['query']),
    'getNewsPost' : IDL.Func([IDL.Text], [IDL.Opt(NewsPost)], ['query']),
    'getNewsPostsByCategory' : IDL.Func(
        [PostCategory],
        [IDL.Vec(NewsPost)],
        ['query'],
      ),
    'getNewsPostsByTimestamp' : IDL.Func([], [IDL.Vec(NewsPost)], ['query']),
    'getScanReport' : IDL.Func([], [ScanReport], ['query']),
    'getTradingSignal' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TradingSignal)],
        ['query'],
      ),
    'getTradingSignalsByCoinName' : IDL.Func(
        [],
        [IDL.Vec(TradingSignal)],
        ['query'],
      ),
    'getTradingSignalsByStatus' : IDL.Func(
        [SignalStatus],
        [IDL.Vec(TradingSignal)],
        ['query'],
      ),
    'getTradingSignalsByTimestamp' : IDL.Func(
        [],
        [IDL.Vec(TradingSignal)],
        ['query'],
      ),
    'getTrendingCoin' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TrendingCoin)],
        ['query'],
      ),
    'getTrendingCoinsByCategory' : IDL.Func(
        [CoinCategory],
        [IDL.Vec(TrendingCoin)],
        ['query'],
      ),
    'getTrendingCoinsByPrice' : IDL.Func(
        [],
        [IDL.Vec(TrendingCoin)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMarketStatus' : IDL.Func([MarketStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };