/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppUserProfile {
  'uid' : string,
  'status' : SubscriptionStatus,
  'username' : string,
  'subscriptionExpiry' : Time,
}
export type CoinCategory = { 'hundredX' : null } |
  { 'trending' : null };
export type Direction = { 'buy' : null } |
  { 'sell' : null };
export type MarketSentiment = { 'bullish' : null } |
  { 'bearish' : null } |
  { 'neutral' : null };
export interface MarketStatus {
  'btcDominance' : number,
  'marketCap' : number,
  'sentiment' : MarketSentiment,
}
export interface NewsPost {
  'title' : string,
  'postCategory' : PostCategory,
  'timestamp' : Time,
  'contentSummary' : string,
}
export type PostCategory = { 'news' : null } |
  { 'post' : null };
export type SignalStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export type SubscriptionStatus = { 'trial' : null } |
  { 'active' : null } |
  { 'expired' : null };
export type Time = bigint;
export interface TrackedTradeRecord {
  'uid' : string,
  'tradeJson' : string,
  'updatedAt' : Time,
  'tradeId' : string,
}
export interface TradingSignal {
  'direction' : Direction,
  'targetPrice' : number,
  'stopLoss' : number,
  'timestamp' : Time,
  'coinName' : string,
  'entryPrice' : number,
  'signalStatus' : SignalStatus,
}
export interface TrendingCoin {
  'currentPrice' : number,
  'change24h' : number,
  'name' : string,
  'predictedTarget' : number,
  'category' : CoinCategory,
  'symbol' : string,
}
export interface UserCredential {
  'uid' : string,
  'username' : string,
  'createdAt' : Time,
  'subscriptionType' : string,
  'passwordHash' : string,
}
export interface UserProfile {
  'status' : SubscriptionStatus,
  'username' : string,
  'subscriptionExpiry' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addAppUserProfile' : ActorMethod<[AppUserProfile], undefined>,
  'addNewsPost' : ActorMethod<[NewsPost], undefined>,
  'addTradingSignal' : ActorMethod<[TradingSignal], undefined>,
  'addTrendingCoin' : ActorMethod<[TrendingCoin], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteTrackedTrade' : ActorMethod<[string], undefined>,
  'deleteUserCredential' : ActorMethod<[string], undefined>,
  'getAllAppUserProfiles' : ActorMethod<[], Array<AppUserProfile>>,
  'getAllNewsPosts' : ActorMethod<[], Array<NewsPost>>,
  'getAllTrackedTrades' : ActorMethod<[], Array<TrackedTradeRecord>>,
  'getAllTradingSignals' : ActorMethod<[], Array<TradingSignal>>,
  'getAllTrendingCoins' : ActorMethod<[], Array<TrendingCoin>>,
  'getAllUserCredentials' : ActorMethod<[], Array<UserCredential>>,
  'getAppUserProfile' : ActorMethod<[string], [] | [AppUserProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMarketStatus' : ActorMethod<[], MarketStatus>,
  'getNewsPost' : ActorMethod<[string], [] | [NewsPost]>,
  'getTrackedTradesForUser' : ActorMethod<[string], Array<TrackedTradeRecord>>,
  'getTradingSignal' : ActorMethod<[string], [] | [TradingSignal]>,
  'getTrendingCoin' : ActorMethod<[string], [] | [TrendingCoin]>,
  'getUserCredentialByUid' : ActorMethod<[string], [] | [UserCredential]>,
  'getUserCredentialByUsername' : ActorMethod<[string], [] | [UserCredential]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveTrackedTrade' : ActorMethod<[TrackedTradeRecord], undefined>,
  'saveUserCredential' : ActorMethod<[UserCredential], undefined>,
  'updateMarketStatus' : ActorMethod<[MarketStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];