/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppUserProfile {
  'uid' : string,
  'status' : SubscriptionStatus,
  'username' : string,
  'subscriptionExpiry' : Time,
}
export type CoinCategory = { 'hundredX' : null } |
  { 'trending' : null };
export type Direction = { 'buy' : null } |
  { 'sell' : null };
export type MarketSentiment = { 'bullish' : null } |
  { 'bearish' : null } |
  { 'neutral' : null };
export interface MarketStatus {
  'btcDominance' : number,
  'marketCap' : number,
  'sentiment' : MarketSentiment,
}
export interface NewsPost {
  'title' : string,
  'postCategory' : PostCategory,
  'timestamp' : Time,
  'contentSummary' : string,
}
export type PostCategory = { 'news' : null } |
  { 'post' : null };
export interface ScanReport {
  'totalSignalsGenerated' : bigint,
  'activeSignalsCount' : bigint,
  'winRate' : number,
  'totalCoinsScanned' : bigint,
}
export type SignalStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export type SubscriptionStatus = { 'trial' : null } |
  { 'active' : null } |
  { 'expired' : null };
export type Time = bigint;
export interface TradingSignal {
  'direction' : Direction,
  'targetPrice' : number,
  'stopLoss' : number,
  'timestamp' : Time,
  'coinName' : string,
  'entryPrice' : number,
  'signalStatus' : SignalStatus,
}
export interface TrendingCoin {
  'currentPrice' : number,
  'change24h' : number,
  'name' : string,
  'predictedTarget' : number,
  'category' : CoinCategory,
  'symbol' : string,
}
export interface UserProfile {
  'status' : SubscriptionStatus,
  'username' : string,
  'subscriptionExpiry' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAppUserProfile' : ActorMethod<[AppUserProfile], undefined>,
  'addNewsPost' : ActorMethod<[NewsPost], undefined>,
  'addTradingSignal' : ActorMethod<[TradingSignal], undefined>,
  'addTrendingCoin' : ActorMethod<[TrendingCoin], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllAppUserProfiles' : ActorMethod<[], Array<AppUserProfile>>,
  'getAllNewsPosts' : ActorMethod<[], Array<NewsPost>>,
  'getAllTradingSignals' : ActorMethod<[], Array<TradingSignal>>,
  'getAllTrendingCoins' : ActorMethod<[], Array<TrendingCoin>>,
  'getAppUserProfile' : ActorMethod<[string], [] | [AppUserProfile]>,
  'getAppUserProfilesByStatus' : ActorMethod<
    [SubscriptionStatus],
    Array<AppUserProfile>
  >,
  'getAppUserProfilesBySubscriptionExpiry' : ActorMethod<
    [],
    Array<AppUserProfile>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMarketStatus' : ActorMethod<[], MarketStatus>,
  'getNewsPost' : ActorMethod<[string], [] | [NewsPost]>,
  'getNewsPostsByCategory' : ActorMethod<[PostCategory], Array<NewsPost>>,
  'getNewsPostsByTimestamp' : ActorMethod<[], Array<NewsPost>>,
  'getScanReport' : ActorMethod<[], ScanReport>,
  'getTradingSignal' : ActorMethod<[string], [] | [TradingSignal]>,
  'getTradingSignalsByCoinName' : ActorMethod<[], Array<TradingSignal>>,
  'getTradingSignalsByStatus' : ActorMethod<
    [SignalStatus],
    Array<TradingSignal>
  >,
  'getTradingSignalsByTimestamp' : ActorMethod<[], Array<TradingSignal>>,
  'getTrendingCoin' : ActorMethod<[string], [] | [TrendingCoin]>,
  'getTrendingCoinsByCategory' : ActorMethod<
    [CoinCategory],
    Array<TrendingCoin>
  >,
  'getTrendingCoinsByPrice' : ActorMethod<[], Array<TrendingCoin>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMarketStatus' : ActorMethod<[MarketStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];