/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TrendingCoin {
    currentPrice: number;
    change24h: number;
    name: string;
    predictedTarget: number;
    category: CoinCategory;
    symbol: string;
}
export type Time = bigint;
export interface ScanReport {
    totalSignalsGenerated: bigint;
    activeSignalsCount: bigint;
    winRate: number;
    totalCoinsScanned: bigint;
}
export interface AppUserProfile {
    uid: string;
    status: SubscriptionStatus;
    username: string;
    subscriptionExpiry: Time;
}
export interface MarketStatus {
    btcDominance: number;
    marketCap: number;
    sentiment: MarketSentiment;
}
export interface NewsPost {
    title: string;
    postCategory: PostCategory;
    timestamp: Time;
    contentSummary: string;
}
export interface TradingSignal {
    direction: Direction;
    targetPrice: number;
    stopLoss: number;
    timestamp: Time;
    coinName: string;
    entryPrice: number;
    signalStatus: SignalStatus;
}
export interface UserProfile {
    status: SubscriptionStatus;
    username: string;
    subscriptionExpiry: Time;
}
export enum CoinCategory {
    hundredX = "hundredX",
    trending = "trending"
}
export enum Direction {
    buy = "buy",
    sell = "sell"
}
export enum MarketSentiment {
    bullish = "bullish",
    bearish = "bearish",
    neutral = "neutral"
}
export enum PostCategory {
    news = "news",
    post = "post"
}
export enum SignalStatus {
    active = "active",
    cancelled = "cancelled",
    completed = "completed"
}
export enum SubscriptionStatus {
    trial = "trial",
    active = "active",
    expired = "expired"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAppUserProfile(profile: AppUserProfile): Promise<void>;
    addNewsPost(post: NewsPost): Promise<void>;
    addTradingSignal(signal: TradingSignal): Promise<void>;
    addTrendingCoin(coin: TrendingCoin): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllAppUserProfiles(): Promise<Array<AppUserProfile>>;
    getAllNewsPosts(): Promise<Array<NewsPost>>;
    getAllTradingSignals(): Promise<Array<TradingSignal>>;
    getAllTrendingCoins(): Promise<Array<TrendingCoin>>;
    getAppUserProfile(uid: string): Promise<AppUserProfile | null>;
    getAppUserProfilesByStatus(status: SubscriptionStatus): Promise<Array<AppUserProfile>>;
    getAppUserProfilesBySubscriptionExpiry(): Promise<Array<AppUserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMarketStatus(): Promise<MarketStatus>;
    getNewsPost(title: string): Promise<NewsPost | null>;
    getNewsPostsByCategory(category: PostCategory): Promise<Array<NewsPost>>;
    getNewsPostsByTimestamp(): Promise<Array<NewsPost>>;
    getScanReport(): Promise<ScanReport>;
    getTradingSignal(coinName: string): Promise<TradingSignal | null>;
    getTradingSignalsByCoinName(): Promise<Array<TradingSignal>>;
    getTradingSignalsByStatus(status: SignalStatus): Promise<Array<TradingSignal>>;
    getTradingSignalsByTimestamp(): Promise<Array<TradingSignal>>;
    getTrendingCoin(name: string): Promise<TrendingCoin | null>;
    getTrendingCoinsByCategory(category: CoinCategory): Promise<Array<TrendingCoin>>;
    getTrendingCoinsByPrice(): Promise<Array<TrendingCoin>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateMarketStatus(status: MarketStatus): Promise<void>;
}
import type { AppUserProfile as _AppUserProfile, CoinCategory as _CoinCategory, Direction as _Direction, MarketSentiment as _MarketSentiment, MarketStatus as _MarketStatus, NewsPost as _NewsPost, PostCategory as _PostCategory, SignalStatus as _SignalStatus, SubscriptionStatus as _SubscriptionStatus, Time as _Time, TradingSignal as _TradingSignal, TrendingCoin as _TrendingCoin, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAppUserProfile(arg0: AppUserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAppUserProfile(to_candid_AppUserProfile_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAppUserProfile(to_candid_AppUserProfile_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addNewsPost(arg0: NewsPost): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNewsPost(to_candid_NewsPost_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNewsPost(to_candid_NewsPost_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTradingSignal(arg0: TradingSignal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTradingSignal(to_candid_TradingSignal_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTradingSignal(to_candid_TradingSignal_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTrendingCoin(arg0: TrendingCoin): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrendingCoin(to_candid_TrendingCoin_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrendingCoin(to_candid_TrendingCoin_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllAppUserProfiles(): Promise<Array<AppUserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppUserProfiles();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppUserProfiles();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNewsPosts(): Promise<Array<NewsPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNewsPosts();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNewsPosts();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTradingSignals(): Promise<Array<TradingSignal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTradingSignals();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTradingSignals();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTrendingCoins(): Promise<Array<TrendingCoin>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrendingCoins();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrendingCoins();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppUserProfile(arg0: string): Promise<AppUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppUserProfile(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppUserProfile(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppUserProfilesByStatus(arg0: SubscriptionStatus): Promise<Array<AppUserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppUserProfilesByStatus(to_candid_SubscriptionStatus_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppUserProfilesByStatus(to_candid_SubscriptionStatus_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppUserProfilesBySubscriptionExpiry(): Promise<Array<AppUserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppUserProfilesBySubscriptionExpiry();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppUserProfilesBySubscriptionExpiry();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketStatus(): Promise<MarketStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketStatus();
                return from_candid_MarketStatus_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketStatus();
            return from_candid_MarketStatus_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsPost(arg0: string): Promise<NewsPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsPost(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsPost(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsPostsByCategory(arg0: PostCategory): Promise<Array<NewsPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsPostsByCategory(to_candid_PostCategory_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsPostsByCategory(to_candid_PostCategory_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsPostsByTimestamp(): Promise<Array<NewsPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsPostsByTimestamp();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsPostsByTimestamp();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScanReport(): Promise<ScanReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getScanReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScanReport();
            return result;
        }
    }
    async getTradingSignal(arg0: string): Promise<TradingSignal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradingSignal(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradingSignal(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradingSignalsByCoinName(): Promise<Array<TradingSignal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradingSignalsByCoinName();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradingSignalsByCoinName();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradingSignalsByStatus(arg0: SignalStatus): Promise<Array<TradingSignal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradingSignalsByStatus(to_candid_SignalStatus_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradingSignalsByStatus(to_candid_SignalStatus_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradingSignalsByTimestamp(): Promise<Array<TradingSignal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradingSignalsByTimestamp();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradingSignalsByTimestamp();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingCoin(arg0: string): Promise<TrendingCoin | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingCoin(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingCoin(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingCoinsByCategory(arg0: CoinCategory): Promise<Array<TrendingCoin>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingCoinsByCategory(to_candid_CoinCategory_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingCoinsByCategory(to_candid_CoinCategory_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingCoinsByPrice(): Promise<Array<TrendingCoin>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingCoinsByPrice();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingCoinsByPrice();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n56(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n56(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateMarketStatus(arg0: MarketStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMarketStatus(to_candid_MarketStatus_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMarketStatus(to_candid_MarketStatus_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AppUserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppUserProfile): AppUserProfile {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_CoinCategory_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoinCategory): CoinCategory {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Direction_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Direction): Direction {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_MarketSentiment_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketSentiment): MarketSentiment {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_MarketStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketStatus): MarketStatus {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_NewsPost_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsPost): NewsPost {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_PostCategory_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostCategory): PostCategory {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_SignalStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalStatus): SignalStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_TradingSignal_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradingSignal): TradingSignal {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_TrendingCoin_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrendingCoin): TrendingCoin {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppUserProfile]): AppUserProfile | null {
    return value.length === 0 ? null : from_candid_AppUserProfile_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NewsPost]): NewsPost | null {
    return value.length === 0 ? null : from_candid_NewsPost_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TradingSignal]): TradingSignal | null {
    return value.length === 0 ? null : from_candid_TradingSignal_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TrendingCoin]): TrendingCoin | null {
    return value.length === 0 ? null : from_candid_TrendingCoin_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    uid: string;
    status: _SubscriptionStatus;
    username: string;
    subscriptionExpiry: _Time;
}): {
    uid: string;
    status: SubscriptionStatus;
    username: string;
    subscriptionExpiry: Time;
} {
    return {
        uid: value.uid,
        status: from_candid_SubscriptionStatus_n24(_uploadFile, _downloadFile, value.status),
        username: value.username,
        subscriptionExpiry: value.subscriptionExpiry
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    postCategory: _PostCategory;
    timestamp: _Time;
    contentSummary: string;
}): {
    title: string;
    postCategory: PostCategory;
    timestamp: Time;
    contentSummary: string;
} {
    return {
        title: value.title,
        postCategory: from_candid_PostCategory_n29(_uploadFile, _downloadFile, value.postCategory),
        timestamp: value.timestamp,
        contentSummary: value.contentSummary
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: _Direction;
    targetPrice: number;
    stopLoss: number;
    timestamp: _Time;
    coinName: string;
    entryPrice: number;
    signalStatus: _SignalStatus;
}): {
    direction: Direction;
    targetPrice: number;
    stopLoss: number;
    timestamp: Time;
    coinName: string;
    entryPrice: number;
    signalStatus: SignalStatus;
} {
    return {
        direction: from_candid_Direction_n34(_uploadFile, _downloadFile, value.direction),
        targetPrice: value.targetPrice,
        stopLoss: value.stopLoss,
        timestamp: value.timestamp,
        coinName: value.coinName,
        entryPrice: value.entryPrice,
        signalStatus: from_candid_SignalStatus_n36(_uploadFile, _downloadFile, value.signalStatus)
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currentPrice: number;
    change24h: number;
    name: string;
    predictedTarget: number;
    category: _CoinCategory;
    symbol: string;
}): {
    currentPrice: number;
    change24h: number;
    name: string;
    predictedTarget: number;
    category: CoinCategory;
    symbol: string;
} {
    return {
        currentPrice: value.currentPrice,
        change24h: value.change24h,
        name: value.name,
        predictedTarget: value.predictedTarget,
        category: from_candid_CoinCategory_n41(_uploadFile, _downloadFile, value.category),
        symbol: value.symbol
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SubscriptionStatus;
    username: string;
    subscriptionExpiry: _Time;
}): {
    status: SubscriptionStatus;
    username: string;
    subscriptionExpiry: Time;
} {
    return {
        status: from_candid_SubscriptionStatus_n24(_uploadFile, _downloadFile, value.status),
        username: value.username,
        subscriptionExpiry: value.subscriptionExpiry
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    btcDominance: number;
    marketCap: number;
    sentiment: _MarketSentiment;
}): {
    btcDominance: number;
    marketCap: number;
    sentiment: MarketSentiment;
} {
    return {
        btcDominance: value.btcDominance,
        marketCap: value.marketCap,
        sentiment: from_candid_MarketSentiment_n51(_uploadFile, _downloadFile, value.sentiment)
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trial: null;
} | {
    active: null;
} | {
    expired: null;
}): SubscriptionStatus {
    return "trial" in value ? SubscriptionStatus.trial : "active" in value ? SubscriptionStatus.active : "expired" in value ? SubscriptionStatus.expired : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    news: null;
} | {
    post: null;
}): PostCategory {
    return "news" in value ? PostCategory.news : "post" in value ? PostCategory.post : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): Direction {
    return "buy" in value ? Direction.buy : "sell" in value ? Direction.sell : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    completed: null;
}): SignalStatus {
    return "active" in value ? SignalStatus.active : "cancelled" in value ? SignalStatus.cancelled : "completed" in value ? SignalStatus.completed : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hundredX: null;
} | {
    trending: null;
}): CoinCategory {
    return "hundredX" in value ? CoinCategory.hundredX : "trending" in value ? CoinCategory.trending : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bullish: null;
} | {
    bearish: null;
} | {
    neutral: null;
}): MarketSentiment {
    return "bullish" in value ? MarketSentiment.bullish : "bearish" in value ? MarketSentiment.bearish : "neutral" in value ? MarketSentiment.neutral : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AppUserProfile>): Array<AppUserProfile> {
    return value.map((x)=>from_candid_AppUserProfile_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NewsPost>): Array<NewsPost> {
    return value.map((x)=>from_candid_NewsPost_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TradingSignal>): Array<TradingSignal> {
    return value.map((x)=>from_candid_TradingSignal_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrendingCoin>): Array<TrendingCoin> {
    return value.map((x)=>from_candid_TrendingCoin_n39(_uploadFile, _downloadFile, x));
}
function to_candid_AppUserProfile_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppUserProfile): _AppUserProfile {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CoinCategory_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoinCategory): _CoinCategory {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_Direction_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): _Direction {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_MarketSentiment_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarketSentiment): _MarketSentiment {
    return to_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function to_candid_MarketStatus_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarketStatus): _MarketStatus {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_NewsPost_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsPost): _NewsPost {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_PostCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostCategory): _PostCategory {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_SignalStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalStatus): _SignalStatus {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): _SubscriptionStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TradingSignal_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradingSignal): _TradingSignal {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_TrendingCoin_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrendingCoin): _TrendingCoin {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: Direction;
    targetPrice: number;
    stopLoss: number;
    timestamp: Time;
    coinName: string;
    entryPrice: number;
    signalStatus: SignalStatus;
}): {
    direction: _Direction;
    targetPrice: number;
    stopLoss: number;
    timestamp: _Time;
    coinName: string;
    entryPrice: number;
    signalStatus: _SignalStatus;
} {
    return {
        direction: to_candid_Direction_n11(_uploadFile, _downloadFile, value.direction),
        targetPrice: value.targetPrice,
        stopLoss: value.stopLoss,
        timestamp: value.timestamp,
        coinName: value.coinName,
        entryPrice: value.entryPrice,
        signalStatus: to_candid_SignalStatus_n13(_uploadFile, _downloadFile, value.signalStatus)
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currentPrice: number;
    change24h: number;
    name: string;
    predictedTarget: number;
    category: CoinCategory;
    symbol: string;
}): {
    currentPrice: number;
    change24h: number;
    name: string;
    predictedTarget: number;
    category: _CoinCategory;
    symbol: string;
} {
    return {
        currentPrice: value.currentPrice,
        change24h: value.change24h,
        name: value.name,
        predictedTarget: value.predictedTarget,
        category: to_candid_CoinCategory_n17(_uploadFile, _downloadFile, value.category),
        symbol: value.symbol
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    uid: string;
    status: SubscriptionStatus;
    username: string;
    subscriptionExpiry: Time;
}): {
    uid: string;
    status: _SubscriptionStatus;
    username: string;
    subscriptionExpiry: _Time;
} {
    return {
        uid: value.uid,
        status: to_candid_SubscriptionStatus_n3(_uploadFile, _downloadFile, value.status),
        username: value.username,
        subscriptionExpiry: value.subscriptionExpiry
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: SubscriptionStatus;
    username: string;
    subscriptionExpiry: Time;
}): {
    status: _SubscriptionStatus;
    username: string;
    subscriptionExpiry: _Time;
} {
    return {
        status: to_candid_SubscriptionStatus_n3(_uploadFile, _downloadFile, value.status),
        username: value.username,
        subscriptionExpiry: value.subscriptionExpiry
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    btcDominance: number;
    marketCap: number;
    sentiment: MarketSentiment;
}): {
    btcDominance: number;
    marketCap: number;
    sentiment: _MarketSentiment;
} {
    return {
        btcDominance: value.btcDominance,
        marketCap: value.marketCap,
        sentiment: to_candid_MarketSentiment_n60(_uploadFile, _downloadFile, value.sentiment)
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    postCategory: PostCategory;
    timestamp: Time;
    contentSummary: string;
}): {
    title: string;
    postCategory: _PostCategory;
    timestamp: _Time;
    contentSummary: string;
} {
    return {
        title: value.title,
        postCategory: to_candid_PostCategory_n7(_uploadFile, _downloadFile, value.postCategory),
        timestamp: value.timestamp,
        contentSummary: value.contentSummary
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): {
    buy: null;
} | {
    sell: null;
} {
    return value == Direction.buy ? {
        buy: null
    } : value == Direction.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalStatus): {
    active: null;
} | {
    cancelled: null;
} | {
    completed: null;
} {
    return value == SignalStatus.active ? {
        active: null
    } : value == SignalStatus.cancelled ? {
        cancelled: null
    } : value == SignalStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoinCategory): {
    hundredX: null;
} | {
    trending: null;
} {
    return value == CoinCategory.hundredX ? {
        hundredX: null
    } : value == CoinCategory.trending ? {
        trending: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): {
    trial: null;
} | {
    active: null;
} | {
    expired: null;
} {
    return value == SubscriptionStatus.trial ? {
        trial: null
    } : value == SubscriptionStatus.active ? {
        active: null
    } : value == SubscriptionStatus.expired ? {
        expired: null
    } : value;
}
function to_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarketSentiment): {
    bullish: null;
} | {
    bearish: null;
} | {
    neutral: null;
} {
    return value == MarketSentiment.bullish ? {
        bullish: null
    } : value == MarketSentiment.bearish ? {
        bearish: null
    } : value == MarketSentiment.neutral ? {
        neutral: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostCategory): {
    news: null;
} | {
    post: null;
} {
    return value == PostCategory.news ? {
        news: null
    } : value == PostCategory.post ? {
        post: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
